CI/DOC: build docs with Python 3.9 due to `doct` package fails on py310
Continuing with doubts...
  nbconvert.utils.pandoc.check_pandoc_version()
reading sources... [ 60%] notebooks/madx

Notebook error:
CellExecutionError in notebooks/madx.ipynb:
------------------
import os
import tfs

for name, doc in hdr2.documents():
    if name == "resource":
        resource_doc = doc
        print(resource_doc)

filename = os.path.join(resource_doc["root"], resource_doc["resource_path"])
df = tfs.read(filename)
------------------

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[5], line 7
      5     if name == "resource":
      6         resource_doc = doc
----> 7         print(resource_doc)
      9 filename = os.path.join(resource_doc["root"], resource_doc["resource_path"])
     10 df = tfs.read(filename)

File /usr/share/miniconda3/envs/sirepo-bluesky-py3.10/lib/python3.10/site-packages/doct.py:134, in Document.__str__(self)
    133 def __str__(self):
--> 134     return vstr(self)

File /usr/share/miniconda3/envs/sirepo-bluesky-py3.10/lib/python3.10/site-packages/doct.py:226, in vstr(doc, indent)
    224 elif name == 'data_keys':
    225     ret += "\n%s" % str(_format_data_keys_dict(value))
--> 226 elif isinstance(value, collections.Mapping):
    227     if '_name' in value:
    228         documents.append((name, value))

AttributeError: module 'collections' has no attribute 'Mapping'

You can ignore this error by setting the following in conf.py:

    nbsphinx_allow_errors = True

make: *** [Makefile:20: html] Error 2
make: Leaving directory '/home/runner/work/sirepo-bluesky/sirepo-bluesky/docs'
Error: Process completed with exit code 2.